(ns ClojuRPG.localisation)

(def welcome-headline "Main headline" "Welcome to the ClojuRPG!")
(def welcome-text "The welcome screen text" "ClojuRGP is a Role-playing game, fully written in Clojure. Althought not graphically astonishing, it has been developed in a dialect of Lisp; poles apart from Flash, JavaScript or any other massively used language!
<br/><br/>ClojuRPG will mesmerise you with it's story and relaibility - who knows, maybe inspire you to write one by yourself")
(def begin-game "Begin adventure button text" "Adventure!")
(def race-choosing-headline "Headline for race chosing screen" "Dawn of the hero")
(def race-choosing-text "Introductory text for race chosing screen" "That misty night, dense fog had set over Amareia - so dense that a weary traveller had to lit two torches, barely to see his way through a sparkling light could be seen from every point in the land. The only night in the year when all races of Amareia could stand one next to another, for this time, it was increadibly peacefull. Humans, Orcs and Elves were at their lands, lookind towards starless sky, into the only light that could break through.
<br/><br/>Suddenly, it started to grow, becoming even lighter and bluish as it made it's way towards the surface. It became obvious that it won't last much above the surface - impact was imminent! Moments after a giant pillar of sparkling smoke arouse from the territory of...")
(def choose-human "Button text for choosing the Human race" "Humans")
(def choose-human-text "Text that describes Human race" "Known to be the wisest ones, healers, priests and grand librarians; Humans are the keepers of the knowledge and history of all Amareia")
(def choose-human-attributes "Human atributes" "Strength 3<br/>Dexterity 2<br/>Intelligence 5")
(def choose-elf "Button text for choosing the Elvish race" "Elves")
(def choose-elf-text "Text that describes Elvish race" "Peacefull nation living in woods, that has learned to become one with the nature. Practise meditation and are incredibly agile hunters")
(def choose-elf-attributes "Elvish atributes" "Strength 2<br/>Dexterity 5<br/>Intelligence 3")
(def choose-orc "Button text for choosing the race of Orcs" "Orcs")
(def choose-orc-text "Text that describes Orcish race" "True noble people, often confused for their brute bloodline cousins the Hell Orcs. With them they only share enormus strength and body constitution")
(def choose-orc-attributes "Orcish atributes" "Strength 5<br/>Dexterity 2<br/>Intelligence 3")
(def human-difficulty-headline "Main headline for Human difficulty selection screen" "A beacon of light")
(def human-difficulty-text "Select difficulty if playing with Humans" "Shining object crash landed in the vincinity of the Forebearers temple - the holiest place for all Humman race. Now resting on the highest mountain, an object fallen from the sky lied there like a beacon of light. Neadless to say, both villagers and schollars were baffled by it's manifestation - each for their own reasons. The wisest of them all, three Grand theorists sat together and resoluted that noone must go near it until it is proven safe.
<br/><br/>They soon gathered a handfull of men, most diverse in profession in order to go up the monuntain and examine the \"Holly\" artifact... As so they did; it was a small boulder - there wasn't anything specical about it except for one thing... It had a lateral opening that was just big enough for a hand to fit in. Underneath it, there was a deeply etched text. It red \"~HERO~\".
<br/><br/>They couldn't find a way to study it - because there was nothing to study; just a plain, drilled and etched rock. Also, it was the hardest rock they have ever seen and they couldn't break even a smallest pebble of it for retrieval to the Grand theorists for further studies... Then an idea sprouted - maybe the secret of it lies in the hollowed tube! Nobody was brave enough to try and reach inside. Their torches were long gone so there was no other way of seeing what lies there, but reaching for it. Nobody had the guts; nobody but the...")
(def human-difficulty-easy "Key of the primary attribute for Easy" ":int")
(def human-difficulty-easy-character "Occupation of the character for Easy" "wise Alchemist")
(def human-difficulty-easy-description "Backstory about Easy difficulty" "Alchemists are the most respected and most powerfull off schollars that ever walked the halls of Forebearers temple. Your future will be as brigth as a platinum reagent!")
(def human-difficulty-medium "Key of the primary attribute for Medium" ":str")
(def human-difficulty-medium-character "Occupation of the character for Medium" "disciplined Monk")
(def human-difficulty-medium-description "Backstory about Medium difficulty" "Don't let the title fool you, Human monks are one of the toughest figters there are! You will learn the paths of enlightment and inner peace - where you shall drain your power from!")
(def human-difficulty-hard "Key of the primary attribute for Hard" ":dex")
(def human-difficulty-hard-character "Occupation of the character for Hard" "fearless Adventurer")
(def human-difficulty-hard-description "Backstory about hard difficulty" "Humans have naturally inquisitive mind and their light spirit is not easily taimed. Although not the most powerfull Human there will be, you will always be on the move!")
(def elf-difficulty-headline "Main headline for Elvish difficulty selection screen" "Minahrean embracers")
(def elf-difficulty-text "Select difficulty if playing with Elves" "Mysterious object fell near a densly populated capital of the elvish lands. Only a small amount of residents dared to abandon the safety of Minahrea - thick brown stone walls, riddled with vines and spruots provided shelter and solace to generations of these pure beings. The wisest of Elves had gathered, and decided to send an expedition towards a landing site. As nobody knew the artifact's origin nor purpose, they decided to send in a diversified team of all professions that Minahrea had.
<br/><br/>The team had been gathered and briefed whitin hours. Truly, only the boldest and nimblest representatives had come - and expedition had set off! Quickly after they came to the mysterious artifact. It was a small boulder - there wasn't anything specical about it except for one thing... It had a lateral opening that was just big enough for a hand to fit in. Underneath it, there was a deeply etched text. It red \"~HERO~\".
<br/><br/>They couldn't find a way to study it - because there was nothing to study; just a plain, drilled and etched rock. Also, it was the hardest rock they have ever seen and they couldn't break even a smallest pebble of it for retrieval to Minahrea for further studies... Then an idea sprouted - maybe the secret of it lies in the hollowed tube! Nobody was brave enough to try and reach inside. Their torches were long gone so there was no other way of seeing what lies there, but reaching for it. Nobody had the guts; nobody but the...")
(def elf-difficulty-easy "Key of the primary attribute for Easy" ":dex")
(def elf-difficulty-easy-character "Occupation of the character for Easy" "swift Ranger")
(def elf-difficulty-easy-description "Backstory about Easy difficulty" "The nimblest of them all, noble Ranger, will take care of you and train you to your fullest! You will be most pleased as his protege/child and live up to your potential!")
(def elf-difficulty-medium "Key of the primary attribute for Medium" ":int")
(def elf-difficulty-medium-character "Occupation of the character for Medium" "serene Sage")
(def elf-difficulty-medium-description "Backstory about Medium difficulty" "Wise Elvish sage will teach you about the ways of ancient Elvish magic. Although not the most powerful Elvish magic is, you will grow into a fastest spellcaster!")
(def elf-difficulty-hard "Key of the primary attribute for Hard" ":str")
(def elf-difficulty-hard-character "Occupation of the character for Hard" "tenacious Shadewalker")
(def elf-difficulty-hard-description "Backstory about hard difficulty" "Highly unpopular among Elves, Shadewalkers, are the ones that decided to give up their speed and agility in exchange for brute strength. You shall not be the strongest Elf, but you will be raised as one!")
(def orc-difficulty-headline "Main headline for Orcish difficulty selection screen" "Pedestal of brilliance and sand")
(def orc-difficulty-text "Select difficulty if playing with Orcs" "Unknown object broke the skies and fell in the middle of a Tharak plane. A long forgotten sacred place for all of Orc, as there once stood a Pillar of forgivness, where two brother races swore on truce. Several wachtowers spotted a strange phenomenon and quickly informed the high council. Orcs were ready to respond and had sent a well prepared expedeiton towards the hart of the just-formed crater.
<br/><br/>Fearlessly they started do decend along a side of it, barely noticing the upcomming sandstorm in the distance. Deep down, it had fused with a sand and formed a symbollical pillar of it own - a pedestal of brilliance and sand. It was a small boulder - there wasn't anything specical about it except for one thing... It had a lateral opening that was just big enough for a hand to fit in. Underneath it, there was a deeply etched text. It red \"~HERO~\".
<br/><br/>They couldn't find a way to study it - because there was nothing to study; just a plain, drilled and etched rock. Also, it was the hardest rock they have ever seen and they couldn't break even a smallest pebble of it for retrieval to Minahrea for further studies... Then an idea sprouted - maybe the secret of it lies in the hollowed tube! Nobody was brave enough to try and reach inside. Their torches were long gone so there was no other way of seeing what lies there, but reaching for it. Nobody had the guts; nobody but the...")
(def orc-difficulty-easy "Key of the primary attribute for Easy" ":str")
(def orc-difficulty-easy-character "Occupation of the character for Easy" "forcefull Duelist")
(def orc-difficulty-easy-description "Backstory about Easy difficulty" "Widely known by it's grand body constitution, Orc Duelists are the most wild of all warriors. Pure in hart, with grat strength and vigilance, you shall be a true defender of peace!")
(def orc-difficulty-medium "Key of the primary attribute for Medium" ":int")
(def orc-difficulty-medium-character "Occupation of the character for Medium" "mighty Wizard")
(def orc-difficulty-medium-description "Backstory about Medium difficulty" "Orcish magic is well known among those that dared to underestimate it. Most powerfull curses and forbidden unholy spells shall be yours to cast in the righteous cause!")
(def orc-difficulty-hard "Key of the primary attribute for Hard" ":dex")
(def orc-difficulty-hard-character "Occupation of the character for Hard" "fierce Bounty Hunter")
(def orc-difficulty-hard-description "Backstory about hard difficulty" "Noone is proud in the land of Orc of what these savages undertake. Infamous assasins that follow no code, except their own. Still, you will grow into a formidable opponent!")
(def human-history-headline "Headline of the Human player history" "The beacon of light")
(def human-history-text "Human history text" "The momment bravest of all men slid the hand in, the boulder started to crack and everyone backed away. The beacon was now shining with even more energy and it became obvious that it won't las long. They all hid behind rough mountain face and covered their ears; loud, high pitched sound originated from now glowing sphere, that woke up every village beneath this holy mountain. For a second, it all stopped. Like a moment in time had frosen, no sound could be heared, no nore ligt beams shoot out of the glowing sphere.
<br/><br/>And then it collapsed - the sphere broke down into millions of pieces of light particles, leaving underneath what was once a boulder, glittering mixture of rock, dust and light. On it, there lied a beautiful Human baby. Baby carrying a glittering tiara with ancient runes transcribed on it. As our heroes proceeded to it, it started to cry - like a through newborn. Inside it's tiara, your later name, ~HERO~ was written.
<br/><br/>The one that put the hand into hollowed rock tube soon accepted you as a part of the family. You were tought tools of the trade, like you would once become what he was. And you had - you became your parent's pride and joy! Everyone knew how good you continued the family profession and everyone was proud of you! From the beginning you were destined to do grat things.
<br/><br/>Then came the famous year when every Human child had to go on it's way of destiny. You decided it would best to meet all the neighbouring races and started preparation for the city of Aniracg - on the borderlands of all three lands. Your parents prepared a feast in your name and by the dusk next day, you were on your way. It took you three days by horse to each it... And there you were - the city of Aniracg!")
(def elf-history-headline "Headline of the Elvish player history" "The band of grass")
(def elf-history-text "Elvish history text" "As soon as the brave Elf had slid his hand to try and find something inside the hollowed rock face, ligh started to emerge from the artifact, ripping the fog like an eagle through the sky. Elves quickly found shelter and covered their eyes because lightbeams were tearing through bolder and going in all directions. They quickly turned and started signaling to their guards on the walls to alert everyone, as this soon became a possible threat to all of Minahrea!
<br/><br/>Abruptly, the lights diminished and the fog appeared thicker than ever. But that were just theit eyes unadapted to the nigh due to massive amounts of luminoucity that had hit them. The bravest of them approached carefullt to that which was one a boulder. Now there lied a beautiful Elvish baby with a grass band around it's ankle. Among ancient runes, one could make out a name. It was ~HERO~.
<br/><br/>The one that put the hand into hollowed rock tube soon accepted you as a part of the family. You were tought tools of the trade, like you would once become what he was. And you had - you became your parent's pride and joy! Everyone knew how good you continued the family profession and everyone was proud of you! From the beginning you were destined to do grat things.
<br/><br/>Then came the famous year when every Elven child had to go on it's way of destiny. You decided it would best to meet all the neighbouring races and started preparation for the city of Aniracg - on the borderlands of all three lands. Your parents prepared a feast in your name and by the dusk next day, you were on your way. It took you one day to each it... And there you were - the city of Aniracg!")
(def orc-history-headline "Headline of the Orcish player history" "A baby in the arms")
(def orc-history-text "Orcish history text" "The bravest of them all valiantly put his hand into the lateral opening and light started to emit, all arond the bouldery-object. Alas, this was nothing for the strong orc, as he and has expedition started to inspect it. Light soon turned into bits and they covered their mouths and noses, by reflex of course, because masks were already protecting them from the sand. Seconds after, a blindingly strong eruption of light happened!
<br/><br/>Everyone looked away from the object, only to hear a baby crying! An Orc baby, lied in the arm of the brave one that had put his hand on stake! Unprotected from the hostile atmosphere, baby Orc just had a Stone wristband. With the sandy winds, brave one could only see the name erched on it, your name. ~HERO~, it soon resonated the crater's bed and it was time to leave.
<br/><br/>The one that put the hand into hollowed rock tube soon accepted you as a part of the family. You were tought tools of the trade, like you would once become what he was. And you had - you became your parent's pride and joy! Everyone knew how good you continued the family profession and everyone was proud of you! From the beginning you were destined to do grat things.
<br/><br/>Then came the famous year when every Orcidh child had to go on it's way of destiny. You decided it would best to meet all the neighbouring races and started preparation for the city of Aniracg - on the borderlands of all three lands. Your parents prepared a feast in your name and by the dusk next day, you were on your way. It took you three days to each it... And there you were - the city of Aniracg!")
;forebearers / Orcish runes